// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EstoqueLoja.API.Models;

public partial class EstoqueLojaContext : DbContext
{
    public EstoqueLojaContext(DbContextOptions<EstoqueLojaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ItensEstoque> ItensEstoques { get; set; }

    public virtual DbSet<Loja> Lojas { get; set; }

    public virtual DbSet<Produto> Produtos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ItensEstoque>(entity =>
        {
            entity.Property(e => e.IdLoj).ValueGeneratedNever();

            entity.HasOne(d => d.IdLojNavigation).WithOne(p => p.ItensEstoque)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItensEstoque_Loja");

            entity.HasOne(d => d.IdProNavigation).WithMany(p => p.ItensEstoques).HasConstraintName("FK_ItensEstoque_Produto");
        });

        modelBuilder.Entity<Loja>(entity =>
        {
            entity.HasKey(e => e.IdLoj).HasName("PK__Loja__0C54DBFB27D3C060");

            entity.Property(e => e.IdLoj).ValueGeneratedNever();
        });

        modelBuilder.Entity<Produto>(entity =>
        {
            entity.HasKey(e => e.IdPro).HasName("PK__Produto__2ACD4C7ECC93EC17");

            entity.Property(e => e.IdPro).ValueGeneratedNever();
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.Property(e => e.IdUse).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}