// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EstoqueLoja.API.Models;

[Table("ItensEstoque")]
public partial class ItensEstoque
{
    public int? IdPro { get; set; }

    [Key]
    public int IdLoj { get; set; }

    public int? QuantidadeIte { get; set; }

    [ForeignKey("IdLoj")]
    [InverseProperty("ItensEstoque")]
    public virtual Loja IdLojNavigation { get; set; }

    [ForeignKey("IdPro")]
    [InverseProperty("ItensEstoques")]
    public virtual Produto IdProNavigation { get; set; }
}