// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EstoqueLoja.API.Models;

[Table("Loja")]
public partial class Loja
{
    [Key]
    public int IdLoj { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NomeLoj { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EnderecoLoj { get; set; }

    [InverseProperty("IdLojNavigation")]
    public virtual ItensEstoque ItensEstoque { get; set; }
}