// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EstoqueLoja.API.Models;

[Table("Usuario")]
public partial class Usuario
{
    [Key]
    public int IdUse { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeUse { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string EmailUse { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string PasswordUse { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string RoleUse { get; set; }
}